publication_name: "Prescribing For Diabetes"
publication_sub_name: "England 2015/16 to 2023/24"
publication_date: "8 August 2024"
responsible_statistician: "Graham Platten"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
full_year: "2023/24"
costs_and_items_excel: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pfd/PfD_2023_2024_costs_and_items_v001.xlsx"
demographics_excel: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pfd/PfD_2023_2024__patient_demographics_v001.xlsx"
background_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pfd/pfd_background_info_methodology_v001.html"
