publication_name: "Prescribing For Diabetes"
publication_sub_name: "England 2015/16 to 2022/23"
publication_date: "10 August 2023"
responsible_statistician: "Graham Platten"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
full_year: "2022/23"
